import {
  combineReducers,
  configureStore,
  getDefaultMiddleware,
} from '@reduxjs/toolkit';

import logger from 'redux-logger';

import {
  registerSlice,
  authSlice,
  getAllDocumentsSlice,
  getAllOrdersSlice,
  getAllProductsSlice,
  getIncomingProductsSlice,
  getMusteriOrdersSlice,
  getOrderDetailSlice,
  getOutgoingProductsSlice,
  getProductDetailSlice,
  getTedarikciOrdersSlice,
  addNewProductSlice,
  updateProductSlice,
  productDeleteSlice,
  addIncomingProductSlice,
  deleteOrderSlice,
  getIncomingTransactionsSlice,
  updateOrderSlice,
  getIncomingProductDetailSlice,
  getOutgoingProductDetailSlice,
  deleteProductFromIncomingProductSlice,
  deleteProductFromOutgoingProductSlice,
  updateIncomingDocProductQuantitySlice,
  updateOutgoingDocProductQuantitySlice,
  addIncomingProductToIncomingProductSlice,
  addOutgoingProductSlice,
  addIncomingProductToOutgoingProductSlice,
  updateOutgoingDocSlice,
  updateIncomingDocSlice,
  addNewOrderSlice,
  getNextDocumentNumberSlice,
  getProductsByCategorySlice,
  addNewCategorySlice,
  getAllCategoriesSlice,
  getUserDetailSlice,
  updateUserSlice,
  updateUserPasswordSlice,
  deleteCategorySlice,
  updateCategorySlice,
  addIncomingProductWithProductsSlice,
  addOutgoingProductWithProductsSlice,
  localProductsSlice,
  addVirtualIncomingDocSlice,
  addProductToIncomingVirtualDocSlice,
  getVirtualIncomingProductDetailSlice,
  deleteProductFromIncomingVirtualDocSlice,
  updateIncomingVirtualDocProductsSlice,
  deleteVirtualIncomingDocSlice,
  addVirtualOutgoingDocSlice,
  addProductToOutgoingVirtualDocSlice,
  getVirtualOutgoingProductDetailSlice,
  updateOutgoingVirtualDocProductsSlice,
  deleteProductFromOutgoingVirtualDocSlice,
  deleteVirtualOutgoingDocSlice,
} from './slice';


const reducer = combineReducers({
  localProducts: localProductsSlice,

  deleteVirtualOutgoingDoc: deleteVirtualOutgoingDocSlice,
  removeProductfromOutgoingDocvirtualDoc: deleteProductFromOutgoingVirtualDocSlice,
  updateOutgoingVirtualDocProducts: updateOutgoingVirtualDocProductsSlice,
  virtualOutgoingProductDetail: getVirtualOutgoingProductDetailSlice,
  addProductToOutgoingVirtualDoc: addProductToOutgoingVirtualDocSlice,
  addVirtualOutgoingDoc: addVirtualOutgoingDocSlice,
  deleteVirtualIncomingDoc: deleteVirtualIncomingDocSlice,
  updateIncomingVirtualDocProducts: updateIncomingVirtualDocProductsSlice,
  removeProductfromIncomingvirtualDoc: deleteProductFromIncomingVirtualDocSlice,
  virtualIncomingProductDetail: getVirtualIncomingProductDetailSlice,
  addProductToIncomingVirtualDoc: addProductToIncomingVirtualDocSlice,
  addVirtualIncomingDoc: addVirtualIncomingDocSlice,
  addOutgoingProductWithProducts: addOutgoingProductWithProductsSlice,
  addIncomingProductWithProducts: addIncomingProductWithProductsSlice,
  updateCategory: updateCategorySlice,
  deleteCategory: deleteCategorySlice,
  updateUserPassword: updateUserPasswordSlice,
  updateUser: updateUserSlice,
  getUserDetail: getUserDetailSlice,
  getProductsByCategory: getProductsByCategorySlice,
  newCategory: addNewCategorySlice,
  getCategories: getAllCategoriesSlice,
  register: registerSlice,
  auth: authSlice,
  getAllProducts: getAllProductsSlice,
  productDetail: getProductDetailSlice,
  getAllOrders: getAllOrdersSlice,
  getTedarikciOrders: getTedarikciOrdersSlice,
  getMusteriOrders: getMusteriOrdersSlice,
  orderDetail: getOrderDetailSlice,
  allDocuments: getAllDocumentsSlice,
  getIncomingProducts: getIncomingProductsSlice,
  getOutgoingProducts: getOutgoingProductsSlice,
  addNewProduct: addNewProductSlice,
  updateProduct: updateProductSlice,
  productDelete: productDeleteSlice,
  addIncomingProduct: addIncomingProductSlice,
  addOutgoingProduct: addOutgoingProductSlice,
  deleteOrder: deleteOrderSlice,
  listTransactions: getIncomingTransactionsSlice,
  updateOrder: updateOrderSlice,
  incomingProductdetail: getIncomingProductDetailSlice,
  outgoingProductdetail: getOutgoingProductDetailSlice,
  updateIncomingProductQuantity: updateIncomingDocProductQuantitySlice,
  updateOutgoingProductQuantity: updateOutgoingDocProductQuantitySlice,
  removeProduct: deleteProductFromIncomingProductSlice,
  removeOutgoingProduct: deleteProductFromOutgoingProductSlice,
  addProductToIncomingProduct: addIncomingProductToIncomingProductSlice,
  addProductToOutgoingProduct: addIncomingProductToOutgoingProductSlice,
  updateOutgoingDoc: updateOutgoingDocSlice,
  updateIncomingDoc: updateIncomingDocSlice,
  newOrder: addNewOrderSlice,
  getNextDocumentNumber: getNextDocumentNumberSlice,

});

export const store = configureStore({
  reducer,
  middleware: getDefaultMiddleware => getDefaultMiddleware().concat(logger),
});
