export { default as authSlice } from './auth-slice';
export { default as getAllProductsSlice } from './get-all-products-slice';
export { default as getProductDetailSlice } from './get-product-detail-slice'
export { default as getAllOrdersSlice } from './get-all-orders-slice'
export { default as getTedarikciOrdersSlice } from './get-tedarikci-orders-slice'
export { default as getMusteriOrdersSlice } from './get-musteri-orders-slice'
export { default as getOrderDetailSlice } from './get-order-detail-slice'
export { default as getAllDocumentsSlice } from './get-all-documents-slice';
export { default as getIncomingProductsSlice } from './get-incoming-products-slice';
export { default as getOutgoingProductsSlice } from './get-outgoing-products-slice';
export { default as addNewProductSlice } from './add-new-product-slice';
export { default as updateProductSlice } from './update-product-slice';
export { default as productDeleteSlice } from './delete-product-slice';
export { default as addIncomingProductSlice } from './add-incoming-product-slice';
export { default as addOutgoingProductSlice } from './add-outgoing-product-slice';
export { default as deleteOrderSlice } from './delete-order-slice';
export { default as getIncomingTransactionsSlice } from './get-incoming-transactions-slice';
export { default as updateOrderSlice } from './update-order-slice';
export { default as getIncomingProductDetailSlice } from './get-incoming-product-detail-slice'
export { default as getOutgoingProductDetailSlice } from './get-outgoing-product-detail-slice'
export { default as updateIncomingDocProductQuantitySlice } from './update-incoming-doc-product-quantity-slice'
export { default as updateOutgoingDocProductQuantitySlice } from './update-outgoing-doc-product-quantity-slice'
export { default as deleteProductFromIncomingProductSlice } from './delete-product-from-incoming-product-slice'
export { default as deleteProductFromOutgoingProductSlice } from './delete-product-from-outgoing-product-slice'
export { default as addIncomingProductToIncomingProductSlice } from './add-incoming-product-to-incoming-product-slice'
export { default as addIncomingProductToOutgoingProductSlice } from './add-incoming-product-to-outgoing-product-slice'
export { default as updateOutgoingDocSlice } from './update-outgoing-doc-slice'
export { default as updateIncomingDocSlice } from './update-incoming-doc-slice'
export { default as addNewOrderSlice } from './add-new-order-slice'
export { default as getNextDocumentNumberSlice } from './get-next-document-number-slice'
export { default as registerSlice } from "./register-slice";
export { default as getAllCategoriesSlice } from "./get-all-categories-slice";
export { default as addNewCategorySlice } from "./add-new-category-slice";
export { default as getProductsByCategorySlice } from "./get-products-by-category-slice";
export { default as getUserDetailSlice } from "./get-user-detail-slice";
export { default as updateUserSlice } from "./update-user-slice";
export { default as updateUserPasswordSlice } from "./update-user-password-slice";
export { default as updateCategorySlice } from "./update-category-slice";
export { default as deleteCategorySlice } from "./delete-category-slice";
export { default as addIncomingProductWithProductsSlice } from "./add-incoming-product-with-products-slice";
export { default as addOutgoingProductWithProductsSlice } from "./add-outgoing-product-with-products-slice";
export { default as addVirtualIncomingDocSlice } from "./add-virtual-incoming-doc-slice";
export { default as addProductToIncomingVirtualDocSlice } from "./add-product-to-incoming-virtual-doc-slice";

export { default as getVirtualIncomingProductDetailSlice } from "./get-virtual-incoming-product-detail-process-slice";
export { default as deleteProductFromIncomingVirtualDocSlice } from "./delete-product-from-incoming-virtual-doc-slice";
export { default as updateIncomingVirtualDocProductsSlice } from "./update-incoming-virtual-doc-products-slice";
export { default as deleteVirtualIncomingDocSlice } from "./delete-virtual-incoming-doc-slice";
export { default as addVirtualOutgoingDocSlice } from "./add-virtual-outgoing-doc-slice";
export { default as addProductToOutgoingVirtualDocSlice } from "./add-product-to-outgoing-virtual-doc-slice";
export { default as getVirtualOutgoingProductDetailSlice } from "./get-virtual-outgoing-product-detail-process-slice";
export { default as updateOutgoingVirtualDocProductsSlice } from "./update-outgoing-virtual-doc-products-slice";
export { default as deleteProductFromOutgoingVirtualDocSlice } from "./delete-product-from-outgoing-virtual-doc-slice";
export { default as deleteVirtualOutgoingDocSlice } from "./delete-virtual-outgoing-doc-slice";


export { default as localProductsSlice } from "./local-products-slice";

